### ISSUE TITLE
SPV checklist

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1000]
## dcrd

- [x] return headers starting at the fork point for a getheaders request (decred/dcrd#427)
  - fixed in btcd by https://github.com/btcsuite/btcd/commit/34b1373a681e0aa3be47ba4fdb5cea815b637b54
- [x] add gcs and gcs/builder packages
- [x] advertise cf support with a service flag when enabled
- [x] bump protocol version for the new service flag and new messages
- [x] support new cf messages in the serverPeer: `getcfheaders`, `getcfilter`, `getcftypes`, `cfheaders`, `cfilter`, `cftypes`
- [x] add json-rpc support for cfilters so wallet can continue to save cfilters to the database when not running in spv mode
- [x] add json-rpc client support for the new RPCs

## dcrwallet

- [x] Basic header verification
  - [x] Check reported difficulty in header is valid
  - [x] Check proof of work against the header's reported difficulty
  - [x] Validate sdiff when DCP0001 deployment is active
  - [x] Validate merkle roots of fetched blocks
  - [x] Validate cfilters of matched and fetched blocks
- [x] Validate that fetched full blocks' transaction merkle trees match the merkle roots in the header
- [x] Save compact filters to DB
  - filter headers will not be saved nor checked at this time, but will need to be handled later for multipeer
  - all filters will be saved so that the client can more quickly perform an "exists address" check, and then only pull blocks which may contain the address
  - database upgrade will be a two step process
    - [x] upgrade schema to add fields for the filters
    - [x] on first start after upgrade, download all missing cfilters
      - this is extremely slow currently and we need a batched request a la getheaders
- [x] Fetch and save cfilters even when running with the JSON-RPC backend
- [x] implement the wallet.NetworkBackend interface using the wire protocol
  - [x] `GetHeaders`
  - [x] `LoadTxFilter`
  - [x] `Rescan`
  - [x] `AddressesUsed` (removing, address usage scanning will get new algorithm)
  - [x] `GetBlock` (new addition to the interface)
  - [x] `GetBlocks` (also new)
  - [x] `PublishTransaction`
  - [x] `StakeDifficulty` (when DCP0001 is active, sdiff will be calculated by the wallet.  this is a fallback when not active, and is only queryable with dcrd RPC)
- [x] `GetBlockHash` (being removed when the dcrd getheaders bug is fixed)
- [x] Implement new DiscoverActiveAddresses algorithm that scans saved cfilters and fetches full blocks
  - ~~new implementation is significantly slower on a lightly used testnet wallet. many places to apply optimization still.~~ fixed
- [x] Implement account restores during DiscoverActiveAddresses
- [x] Add DNS peer discovery
- [x] Add P2P peer discovery
- [x] Implement multipeer syncing
- [x] Disconnect from peers behind our main chain
- [x] ~Disconnect peers that aren't announcing new blocks announced by other peers within some time limit~ ignoring for now, dcrd has same issue currently
- [x] Remove reorg handling as it is currently performed through dcrd notifications and replace with determining locally which is the best fork
  - [x] Implement sidechain and orphan block management
  - [x] Choose best sidechain based on total work, not height
- [x] Listen for transaction invs and save unmined transactions which are relevant to the wallet
  - May need some protection and additional data in the unmined transaction records in the database to prevent announcing invalid transactions to other peers
- [x] Write a new ticketbuyer that doesn't rely on dcrd RPC.
- [x] Disable certain functionality when operating in SPV mode
  - [x] Voting (winning tickets are not in the header nor is there anything anchoring them with a merkleroot)
  - [x] Revoking missed tickets before their expiry period (unknown whether the ticket is live or missed)

**Comment by vctt94** [comment]
Can I work on `Disable certain functionality when operating in SPV mode `?

**Comment by jrick** [comment]
All items have been completed.  See #1213 for implementation.
